# Generated by Django 3.2.9 on 2021-11-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=128, null=True)),
                ('item_name', models.CharField(max_length=256)),
                ('item_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('item_remark', models.CharField(blank=True, max_length=512, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('updated_by', models.BigIntegerField()),
            ],
        ),
    ]
