# Generated by Django 3.2.9 on 2021-11-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
