# Generated by Django 3.2.9 on 2021-11-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211128_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
