# Generated by Django 3.2.9 on 2021-11-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_item_item_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_amount',
            new_name='current_stock',
        ),
    ]
