# Generated by Django 3.2.9 on 2021-11-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_item_amount_item_current_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='current_stock',
            new_name='in_stock',
        ),
    ]
