# Generated by Django 3.2.9 on 2021-11-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_item_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default='####', max_length=128),
        ),
    ]
