# Generated by Django 3.2.9 on 2021-12-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_item_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flowType', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('flowChannel', models.CharField(choices=[('Buy', 'Buy'), ('Facebook', 'Facebook'), ('Shopee', 'Shopee'), ('Lazada', 'Lazada')], max_length=10)),
                ('amount', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
