# Generated by Django 3.2.9 on 2021-12-02 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='updateBy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
