# Generated by Django 3.2.9 on 2021-12-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20211202_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='itemId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
