# Generated by Django 3.2.9 on 2021-12-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_inventory_itemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundleSKU', models.CharField(max_length=64)),
                ('bundleName', models.CharField(max_length=64)),
                ('isShopee', models.BooleanField(default=True)),
                ('isLazada', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=128, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BundleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundleId', models.BigIntegerField()),
                ('item_id', models.BigIntegerField()),
                ('item_amount', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='flowChannel',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Facebook', 'Facebook'), ('Shopee', 'Shopee'), ('Lazada', 'Lazada'), ('Manual', 'Manual')], max_length=10),
        ),
    ]
