# Generated by Django 3.2.9 on 2021-12-06 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20211204_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundledetail',
            name='bundleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bundle'),
        ),
    ]
