# Generated by Django 3.2.9 on 2021-12-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_bundledetail_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bundleDescription',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
